version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: pencool/foodgram_back:v1
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: pencool/foodgram_front:v1
    volumes:
      - ../frontend/:/backend/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db_postgres:
  static_value:
  media_value:
